### ISSUE TITLE
Not Able to use render-if 

### ISSUE THREAD

**Issue by consentsam** [ajwhite/render-if#15]
I am getting following error when i tried using the render-if in a basic code

error: bundling: UnableToResolveError: Unable to resolve module `./renderIf` from `/root/example/index.android.js`: Directory /root/example/renderIf doesn't exist
    at UnableToResolveError (/root/example/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:612:5)
    at ResolutionRequest._loadAsDir (/root/example/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:572:13)
    at tryResolveSync (/root/example/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:411:18)
    at tryResolveSync (/root/example/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:89:12)
    at ResolutionRequest._resolveFileOrDir (/root/example/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:409:12)
    at ResolutionRequest._resolveNodeDependency (/root/example/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:417:19)
    at ResolutionRequest.resolveDependency (/root/example/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:135:29)
    at dependencyNames.map.name (/root/example/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:142:59)
    at Array.map (native)
    at ResolutionRequest.resolveModuleDependencies (/root/example/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:142:42)
Bundling `index.android.js`  0.0% (0/534), failed.

Please have a look at this problem.

**Comment by atticoos** [comment]
Make sure you double check how you're importing modules, like `render-if`

**Comment by consentsam** [comment]
Thanks for replying !!
And Sorry for asking such a silly doubt.

**Comment by atticoos** [comment]
Glad to hear you got it sorted out 👍
